# fly.toml app configuration file for linkedin-content-backend-staging
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkedin-content-backend-staging"
primary_region = "mad"

[build]
  dockerfile = "Dockerfile.python"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
  FLASK_APP = "wsgi.py"
  FLASK_ENV = "staging"
  ENVIRONMENT = "staging"
  CORS_ORIGINS = "http://localhost:3000,https://linkedin-content-frontend-staging.vercel.app"
  GOOGLE_CLOUD_STORAGE_BUCKET = "paa-some-videos-staging"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 250

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9091
  path = "/metrics" 