# fly.toml app configuration file generated for linkedin-content-backend on 2025-03-09T09:50:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkedin-content-backend"
primary_region = "mad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health/live"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
