[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "linkedin-content-backend"
version = "0.1.0"
description = "LinkedIn Content Backend"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["app"] 